% Demo code for mapping cortical thickness difference using MBM.
% This demo uses the thickness maps generated by the framework described in
% the MBM paper. In particular, 25 maps were generated from each of the two
% ground truths. The list of maps' filenames is in 'map_list.txt'.  The
% design matrix that identifies the two groups of the maps is stored in
% 'G_two_sample.txt'. All input files are stored in 'data/demo_1' folder.
% Using MBM, we obtain the \beta spectrum, significant pattern that
% comprises the weighted significant modes, and a number of the most influential modes.

clear all
close all

rng(2); % set the default seed for random generation to ensure the results are reproducible.

wdir = pwd();
dataDir = fullfile(wdir, 'data', 'demo_1');

% make map list file by adding dataDir
maps = table2cell(readtable(fullfile(dataDir,'map.txt'), 'delimiter', '\t', 'ReadVariableNames', false));

MBM.maps.anatListFile = fullfile(dataDir, 'map_list.txt'); % text file comprise the list of paths to the anatomical maps
writelines(fullfile(dataDir, 'thickness', maps), MBM.maps.anatListFile);

MBM.maps.maskFile = fullfile(dataDir, 'mask_S1200.L.midthickness_MSMAll.32k_fs_LR.txt'); % path to mask

MBM.stat.test = 'two sample'; % statistical test

MBM.stat.designFile = fullfile(dataDir, 'G_two_sample.txt'); % path to design matrix

MBM.stat.nPer = 10; % number0 of permutations
MBM.stat.pThr = 0.1; % threshold for tail estimation
MBM.stat.thres = 0.05; % statistical threshold to be considered significant
MBM.stat.fdr = false; % FDR correction

MBM.eig.eigFile = fullfile(dataDir, 'evec_501_masked_S1200.L.midthickness_MSMAll.32k_fs_LR.txt'); % path to eigenmode file
MBM.eig.nEigenmode = 150; % number of eigenmodes for analysis

MBM.eig.saveResult = true; % save the results, i.e., MBM structure
MBM.eig.resultFile = fullfile(dataDir,'mbm_demo_1.mat'); % where to save the results

MBM.plot.visualize = true; % visualise the results
MBM.plot.saveFig = true; % save the visualisation of the results
MBM.plot.figFile = fullfile(dataDir, 'demo_1.fig'); % where to save the visualisation of the results.
MBM.plot.vtkFile = fullfile(dataDir, 'fsLR_32k_midthickness-lh.vtk'); % path to vtk file
MBM.plot.hemis = 'left'; % hemisphere to be analysed
MBM.plot.nInfluentialMode = 6; % number of most influential modes to be plotted

MBM = mbm_main(MBM);
